export const ROOMS_LIST_REQUEST = "ROOMS_LIST_REQUEST"
export const ROOMS_LIST_SUCCESS = "ROOMS_LIST_SUCCESS"
export const ROOMS_LIST_FAIL = "ROOMS_LIST_FAIL"

export const ROOM_DETAIL_REQUEST = "ROOM_DETAIL_REQUEST"
export const ROOM_DETAIL_SUCCESS = "ROOM_DETAIL_SUCCESS"
export const ROOM_DETAIL_FAIL = "ROOM_DETAIL_FAIL"

export const ROOM_CREATE_REQUEST = "ROOM_CREATE_REQUEST"
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS"
export const ROOM_CREATE_FAIL = "ROOM_CREATE_FAIL"

export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST"
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS"
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL"

export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST"
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS"
export const MESSAGE_CREATE_FAIL = "MESSAGE_CREATE_FAIL"

export const TOPIC_LIST_REQUEST = "TOPIC_LIST_REQUEST"
export const TOPIC_LIST_SUCCESS = "TOPIC_LIST_SUCCESS"
export const TOPIC_LIST_FAIL = "TOPIC_LIST_FAIL"